import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Using CSS custom properties from tokens.css (IBM-based)
        primary: 'var(--color-accent-primary)',
        neutral: {
          50: 'var(--ibm-warm-gray-10)',
          100: 'var(--ibm-warm-gray-20)',
          200: 'var(--ibm-warm-gray-30)',
          300: 'var(--ibm-warm-gray-40)',
          400: 'var(--ibm-warm-gray-50)',
          500: 'var(--ibm-warm-gray-60)',
          600: 'var(--ibm-warm-gray-70)',
          700: 'var(--ibm-warm-gray-80)',
          800: 'var(--ibm-warm-gray-90)',
          900: 'var(--ibm-warm-gray-100)',
        },
        gray: {
          10: 'var(--ibm-gray-10)',
          20: 'var(--ibm-gray-20)',
          30: 'var(--ibm-gray-30)',
          40: 'var(--ibm-gray-40)',
          50: 'var(--ibm-gray-50)',
          60: 'var(--ibm-gray-60)',
          70: 'var(--ibm-gray-70)',
          80: 'var(--ibm-gray-80)',
          90: 'var(--ibm-gray-90)',
          100: 'var(--ibm-gray-100)',
        },
        coolGray: {
          10: 'var(--ibm-cool-gray-10)',
          20: 'var(--ibm-cool-gray-20)',
          30: 'var(--ibm-cool-gray-30)',
          40: 'var(--ibm-cool-gray-40)',
          50: 'var(--ibm-cool-gray-50)',
          60: 'var(--ibm-cool-gray-60)',
          70: 'var(--ibm-cool-gray-70)',
          80: 'var(--ibm-cool-gray-80)',
          90: 'var(--ibm-cool-gray-90)',
          100: 'var(--ibm-cool-gray-100)',
        },
        blue: {
          10: 'var(--ibm-blue-10)',
          20: 'var(--ibm-blue-20)',
          30: 'var(--ibm-blue-30)',
          40: 'var(--ibm-blue-40)',
          50: 'var(--ibm-blue-50)',
          60: 'var(--ibm-blue-60)',
          70: 'var(--ibm-blue-70)',
          80: 'var(--ibm-blue-80)',
          90: 'var(--ibm-blue-90)',
          100: 'var(--ibm-blue-100)',
        },
        cyan: {
          10: 'var(--ibm-cyan-10)',
          20: 'var(--ibm-cyan-20)',
          30: 'var(--ibm-cyan-30)',
          40: 'var(--ibm-cyan-40)',
          50: 'var(--ibm-cyan-50)',
          60: 'var(--ibm-cyan-60)',
          70: 'var(--ibm-cyan-70)',
          80: 'var(--ibm-cyan-80)',
          90: 'var(--ibm-cyan-90)',
          100: 'var(--ibm-cyan-100)',
        },
        teal: {
          10: 'var(--ibm-teal-10)',
          20: 'var(--ibm-teal-20)',
          30: 'var(--ibm-teal-30)',
          40: 'var(--ibm-teal-40)',
          50: 'var(--ibm-teal-50)',
          60: 'var(--ibm-teal-60)',
          70: 'var(--ibm-teal-70)',
          80: 'var(--ibm-teal-80)',
          90: 'var(--ibm-teal-90)',
          100: 'var(--ibm-teal-100)',
        },
        green: {
          10: 'var(--ibm-green-10)',
          20: 'var(--ibm-green-20)',
          30: 'var(--ibm-green-30)',
          40: 'var(--ibm-green-40)',
          50: 'var(--ibm-green-50)',
          60: 'var(--ibm-green-60)',
          70: 'var(--ibm-green-70)',
          80: 'var(--ibm-green-80)',
          90: 'var(--ibm-green-90)',
          100: 'var(--ibm-green-100)',
        },
        red: {
          10: 'var(--ibm-red-10)',
          20: 'var(--ibm-red-20)',
          30: 'var(--ibm-red-30)',
          40: 'var(--ibm-red-40)',
          50: 'var(--ibm-red-50)',
          60: 'var(--ibm-red-60)',
          70: 'var(--ibm-red-70)',
          80: 'var(--ibm-red-80)',
          90: 'var(--ibm-red-90)',
          100: 'var(--ibm-red-100)',
        },
        orange: {
          10: 'var(--ibm-orange-10)',
          20: 'var(--ibm-orange-20)',
          30: 'var(--ibm-orange-30)',
          40: 'var(--ibm-orange-40)',
          50: 'var(--ibm-orange-50)',
          60: 'var(--ibm-orange-60)',
          70: 'var(--ibm-orange-70)',
          80: 'var(--ibm-orange-80)',
          90: 'var(--ibm-orange-90)',
          100: 'var(--ibm-orange-100)',
        },
        magenta: {
          10: 'var(--ibm-magenta-10)',
          20: 'var(--ibm-magenta-20)',
          30: 'var(--ibm-magenta-30)',
          40: 'var(--ibm-magenta-40)',
          50: 'var(--ibm-magenta-50)',
          60: 'var(--ibm-magenta-60)',
          70: 'var(--ibm-magenta-70)',
          80: 'var(--ibm-magenta-80)',
          90: 'var(--ibm-magenta-90)',
          100: 'var(--ibm-magenta-100)',
        },
        purple: {
          10: 'var(--ibm-purple-10)',
          20: 'var(--ibm-purple-20)',
          30: 'var(--ibm-purple-30)',
          40: 'var(--ibm-purple-40)',
          50: 'var(--ibm-purple-50)',
          60: 'var(--ibm-purple-60)',
          70: 'var(--ibm-purple-70)',
          80: 'var(--ibm-purple-80)',
          90: 'var(--ibm-purple-90)',
          100: 'var(--ibm-purple-100)',
        },
        yellow: {
          10: 'var(--ibm-yellow-10)',
          20: 'var(--ibm-yellow-20)',
          30: 'var(--ibm-yellow-30)',
          40: 'var(--ibm-yellow-40)',
          50: 'var(--ibm-yellow-50)',
          60: 'var(--ibm-yellow-60)',
          70: 'var(--ibm-yellow-70)',
          80: 'var(--ibm-yellow-80)',
          90: 'var(--ibm-yellow-90)',
          100: 'var(--ibm-yellow-100)',
        },
        layer: {
          bg: 'var(--color-layer-bg)',
          1: 'var(--color-layer-1)',
          2: 'var(--color-layer-2)',
          3: 'var(--color-layer-3)',
          4: 'var(--color-layer-4)',
          5: 'var(--color-layer-5)',
          6: 'var(--color-layer-6)',
          7: 'var(--color-layer-7)',
          8: 'var(--color-layer-8)',
          surface: 'var(--color-layer-surface)',
        },
        accent: 'var(--color-accent-primary)',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      spacing: {
        // Using CSS custom properties
      },
      borderRadius: {
        DEFAULT: 'var(--radius-sm)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-md)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      transitionDuration: {
        DEFAULT: 'var(--duration-normal)',
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
        slow: 'var(--duration-slow)',
      },
      transitionTimingFunction: {
        DEFAULT: 'var(--easing-standard)',
      },
    },
  },
  plugins: [],
}
export default config
